// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecognitionComponent;

namespace RecognitionComponent.Migrations
{
    [DbContext(typeof(ImageContext))]
    partial class ImageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("RecognitionComponent.BBox", b =>
                {
                    b.Property<int>("BBoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X1")
                        .HasColumnType("REAL");

                    b.Property<float>("X2")
                        .HasColumnType("REAL");

                    b.Property<float>("Y1")
                        .HasColumnType("REAL");

                    b.Property<float>("Y2")
                        .HasColumnType("REAL");

                    b.HasKey("BBoxId");

                    b.HasIndex("ResultEntityId")
                        .IsUnique();

                    b.ToTable("BBoxes");
                });

            modelBuilder.Entity("RecognitionComponent.ImageEntity", b =>
                {
                    b.Property<int>("ImageEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.HasKey("ImageEntityId");

                    b.ToTable("ImageEntities");
                });

            modelBuilder.Entity("RecognitionComponent.ResultEntity", b =>
                {
                    b.Property<int>("ResultEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int>("ImageEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("ResultEntityId");

                    b.HasIndex("ImageEntityId");

                    b.ToTable("ResultEntities");
                });

            modelBuilder.Entity("RecognitionComponent.BBox", b =>
                {
                    b.HasOne("RecognitionComponent.ResultEntity", "ResultEntity")
                        .WithOne("BBox")
                        .HasForeignKey("RecognitionComponent.BBox", "ResultEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultEntity");
                });

            modelBuilder.Entity("RecognitionComponent.ResultEntity", b =>
                {
                    b.HasOne("RecognitionComponent.ImageEntity", "ImageEntity")
                        .WithMany("Results")
                        .HasForeignKey("ImageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageEntity");
                });

            modelBuilder.Entity("RecognitionComponent.ImageEntity", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("RecognitionComponent.ResultEntity", b =>
                {
                    b.Navigation("BBox");
                });
#pragma warning restore 612, 618
        }
    }
}
